---
- name: Configuring the HA for the fortigate secondary in AWS for active-passive mode
  hosts: localhost
  vars:
    host: "<your_host>"
    username: "admin"
    password: "<password>"
    vdom: "root"
    ssl_verify: "False"   
  tasks:
  - name: Configure HA    
    fortinet.fortios.fortios_system_ha:
      host: "{{ host }}"
      username: "{{ username  }}"
      password: "{{ password  }}"
      vdom: "{{ vdom  }}"
      https: "True"
      system_ha:
        group_name: "aws_fortigate"
        mode: "a-p"
        priority: 150
        hbdev: "port2"
        unicast_hb: "enable"
        unicast_hb_netmask: "255.255.255.224"
        unicast_hb_peerip: "192.168.100.74"
